FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o device-service .

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/device-service .
EXPOSE 8082
CMD ["./device-service"]